In [50]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

In [41]:

df = pd.read_csv("Instagram_Analytics.csv")


df = df.drop(columns=['post_id',"account_id","post_datetime","post_date"])
df.columns

Index(['account_type', 'follower_count', 'media_type', 'content_category',
       'traffic_source', 'has_call_to_action', 'post_hour', 'day_of_week',
       'likes', 'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count', 'performance_bucket_label'],
      dtype='str')

In [42]:
df["hour_sin"] = np.sin(df['post_hour'] * (2 * np.pi / 24))
df["hour_cos"] = np.cos(df['post_hour'] * (2 * np.pi / 24))

day_matching = {
    'Monday': 0,
    'Tuesday': 1,
    'Wednesday': 2,
    'Thursday': 3,
    'Friday': 4,
    'Saturday': 5,
    'Sunday': 6
}

df['day_of_week'] = df['day_of_week'].str.strip()

df['day_of_week'] = df['day_of_week'].map(day_matching)

df['day_sin'] = np.sin(df['day_of_week'] * (2 * np.pi / 7))
df['day_cos'] = np.cos(df['day_of_week'] * (2 * np.pi / 7))

df = df.drop(columns=["post_hour","day_of_week"])

df.head()

,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,likes,comments,shares,saves,...,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label,hour_sin,hour_cos,day_sin,day_cos
0,brand,3551,reel,Technology,Home Feed,1,194,5,7,34,...,6230,0.0385,899,100,7,medium,1.000000,6.123234e-17,-0.974928,-0.222521
1,creator,31095,image,Fitness,Hashtags,1,449,10,21,68,...,8268,0.0663,805,122,5,viral,-0.707107,-7.071068e-01,-0.433884,-0.900969
2,brand,8167,reel,Beauty,Reels Feed,0,114,2,1,22,...,2616,0.0531,758,115,8,high,-0.866025,-5.000000e-01,0.433884,-0.900969
3,creator,9044,carousel,Music,External,0,91,0,7,0,...,3171,0.0309,402,115,7,medium,0.707107,7.071068e-01,0.433884,-0.900969
4,creator,15986,reel,Technology,Profile,0,154,8,5,21,...,8503,0.0221,155,112,9,low,0.707107,-7.071068e-01,-0.433884,-0.900969

In [43]:
df["target"] = df["performance_bucket_label"].apply(lambda x:1 if str(x).strip().lower() in ['high', 'viral'] else 0)

df.head()

,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,likes,comments,shares,saves,...,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label,hour_sin,hour_cos,day_sin,day_cos,target
0,brand,3551,reel,Technology,Home Feed,1,194,5,7,34,...,0.0385,899,100,7,medium,1.000000,6.123234e-17,-0.974928,-0.222521,0
1,creator,31095,image,Fitness,Hashtags,1,449,10,21,68,...,0.0663,805,122,5,viral,-0.707107,-7.071068e-01,-0.433884,-0.900969,1
2,brand,8167,reel,Beauty,Reels Feed,0,114,2,1,22,...,0.0531,758,115,8,high,-0.866025,-5.000000e-01,0.433884,-0.900969,1
3,creator,9044,carousel,Music,External,0,91,0,7,0,...,0.0309,402,115,7,medium,0.707107,7.071068e-01,0.433884,-0.900969,0
4,creator,15986,reel,Technology,Profile,0,154,8,5,21,...,0.0221,155,112,9,low,0.707107,-7.071068e-01,-0.433884,-0.900969,0

In [44]:
metric_columns = ['likes', 'comments', 'shares', 'saves', 'reach', 'impressions', 
                     'engagement_rate', 'followers_gained', 'performance_bucket_label']
df = df.drop(columns=metric_columns)
categorical_columns = ['account_type', 'media_type', 'content_category', 'traffic_source']

df_ready = pd.get_dummies(df,columns=categorical_columns,drop_first=True)

In [52]:
df_ready.to_csv("Instagram_Analytics_organized.csv")

In [51]:
X = df_ready.drop(columns="target").astype(np.float32)
y = df_ready["target"].astype(np.float32)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
len(X_train), len(X_test)

(23999, 6000)